config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: %i[index new create edit update] do
    collection do
      get 'all_bookings'
      get 'search'
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get '/assign_roles', to: 'user_managment#assign_roles', as: 'assign_roles'
  put '/update_role', to: 'user_managment#update_role', as: 'update_role'

  get '/list_users', to: 'user_managment#users_list_for_admins', as: 'users_list_for_admins'
  put '/block_user', to: 'user_managment#block_user', as: 'block_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
	# elasticserach
	searchkick

	validates :booking_date, :name, presence: true
	validate :validating_booking_date

	belongs_to :user

	def validating_booking_date
    if booking_date.present? && booking_date.to_date < Date.today
      errors.add(:booking_date, "must be greater than today date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings

  def admin?
    role == 'admin'
  end

  def super_admin?
    role == 'super_admin'
  end

  def user?
    role == 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit::Authorization

	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to root_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[ show edit update destroy ]
  include BookingsHelper

  def index
    authorize current_user, policy_class: UserPolicy

    @bookings = current_user.bookings.where('booking_date > ?', Date.today).order(:created_at)
  rescue Pundit::NotAuthorizedError
    flash[:alert] = "You are Blocked or Not authorized to this page"
    redirect_to root_path
  end

  def new
    authorize current_user, policy_class: UserPolicy

    @booking = Booking.new
  rescue Pundit::NotAuthorizedError
    flash[:alert] = "You are Blocked or Not authorized to this page"
    redirect_to root_path
  end

  def edit
    authorize current_user, policy_class: UserPolicy
  end

  def update
    authorize current_user, policy_class: UserPolicy

    if @booking.update(status: params[:booking][:status])
      redirect_to all_bookings_bookings_path, notice: 'Booking Status was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    authorize current_user, policy_class: UserPolicy

    @booking = Booking.new(booking_params.merge({user_id: current_user.id}))

    if @booking.save
      redirect_to bookings_path, notice: "Booking was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def all_bookings
    authorize current_user, policy_class: UserPolicy
    
    @bookings = Booking.where('booking_date > ?', Date.today).order(:created_at)
  end

  def search
    @bookings = Booking.search(
      params[:search],
      where: {
        booking_date: { gt: Date.today }
      }
    )
    @bookings = Booking.search(where: { booking_date: { gt: Date.today }}) unless params[:search].present?
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:booking_date, :name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/user_managment_controller.rb
class UserManagmentController < ApplicationController
	before_action :authenticate_user!

	def assign_roles
		authorize current_user, policy_class: UserPolicy

		@users = User.where.not(id: current_user.id)
	end

	def update_role
		authorize current_user, policy_class: UserPolicy

		user = User.find(params[:user][:id])

		if user.present?
			user.update(role: params[:role])
      redirect_to assign_roles_path, notice: "Role updated"
    else
      render :assign_roles, status: :unprocessable_entity
    end
	end

	def users_list_for_admins
		authorize current_user, policy_class: UserPolicy

		@users = User.where(role: 'user')
	end

	def block_user
		authorize current_user, policy_class: UserPolicy
		
		user = User.find(params[:user][:id])

		if user.present?
			user.update(is_blocked: params[:user][:is_blocked])
      redirect_to users_list_for_admins_path, notice: "User (#{user.email}) Stats updated"
    else
      render :assign_roles, status: :unprocessable_entity
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
	def get_button_color(status)
		case status
		when 'pending'
			'btn-outline-warning'
		when 'approved'
		  'btn-outline-success'
		when 'rejected'
			'btn-outline-danger'
		end
	end
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div><br>

  <div>
    <%= form.label :booking_date, style: "display: block" %>
    <%= form.datetime_field :booking_date %>
  </div>

  <div>
    <%= form.submit 'Submit', class: 'btn btn-success my-1' %>
  </div>
<% end %>

app/views/bookings/all_bookings.html.erb
<div class="container">

  <h1>Review Bookings (<%= @bookings.count %>)</h1>
  <div class="mb-3">
    <%= form_tag(search_bookings_path, method: :get) do %>
      <%= label_tag :search  %>
      <%= text_field_tag :search  %>
      <%= submit_tag 'search', class: 'btn btn-sm btn-dark'  %>
    <% end %>
  </div>

  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-sm-4 mb-3 mb-1">
        <div class="card">
          <div class="card-body">
            <% button_color = get_button_color(booking.status) %>
            <h5 class="card-title"><%= booking.name %></h5>
            <p class="card-title"><%= booking.booking_date.strftime("%m-%d-%Y %l:%M %p") %> <a href="#" class="btn btn-sm <%=button_color%>"><%= booking.status&.capitalize %></a></p>
            <p><%= link_to 'Review', edit_booking_path(booking), class: 'btn btn-primary' %> Booked by <%= booking.user.email %></p>
          </div>
        </div>
      </div>      
    <% end %>

  </div>

</div>

app/views/bookings/edit.html.erb
<div class="container">
  <h1>New booking</h1>

  <%= form_with(model: @booking) do |form| %>

    <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.select :status, options_for_select([['Approved', 'approved'], ['Rejected', 'rejected']])  %>
    </div>

    <div>
      <%= form.submit 'Submit', class: 'btn btn-success my-1' %>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Back to bookings", all_bookings_bookings_path, class: 'btn btn-sm btn-warning' %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">

  <h1>Bookings (<%= @bookings.count %>)</h1>
  <%= link_to "+ Creating Booking", new_booking_path, class: 'btn btn-success my-1' %>

  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-sm-4 mb-3 mb-1">
        <div class="card">
          <div class="card-body">
            <% button_color = get_button_color(booking.status) %>
            <h5 class="card-title"><%= booking.name %></h5>
            <p class="card-title"><%= booking.booking_date.strftime("%m-%d-%Y %l:%M %p") %> <a href="#" class="btn <%=button_color%>"><%= booking.status&.capitalize %></a></p>
          </div>
        </div>
      </div>      
    <% end %>

  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1>New booking</h1>

  <%= render "form", booking: @booking %>

  <br>

  <div>
    <%= link_to "Back to bookings", bookings_path, class: 'btn btn-sm btn-warning' %>
  </div>
</div>

app/views/bookings/search.html.erb
<div class="container">
	<h1>Search (<%= @bookings.count %>)</h1>
  <% if policy(current_user).all_bookings? %>
    <%= link_to 'Back to Bookings', all_bookings_bookings_path, class: 'btn btn-sm btn-warning mb-2' %>
  <% else %>
    <%= link_to 'Back to Bookings', bookings_path, class: 'btn btn-sm btn-warning mb-2' %>
  <% end %>
  <div class="row">
  	<% @bookings.each do |booking| %>
      <div class="col-sm-4 mb-3 mb-1">
        <div class="card">
          <div class="card-body">
            <% button_color = get_button_color(booking.status) %>
            <h5 class="card-title"><%= booking.name %></h5>
            <p class="card-title"><%= booking.booking_date.strftime("%m-%d-%Y %l:%M %p") %> <a href="#" class="btn btn-sm <%=button_color%>"><%= booking.status&.capitalize %></a></p>
            <% if policy(current_user).update? %>
	            <p><%= link_to 'Review', edit_booking_path(booking), class: 'btn btn-primary' %> Booked by <%= booking.user.email %></p>
            <% end %>
          </div>
        </div>
      </div>      
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
	<h1>Welcome to Ticket Booking Application</h1>
	<div id="carouselExampleIndicators" class="carousel slide">
	  <div class="carousel-indicators">
	    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
	    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
	    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
	  </div>
	  <div class="carousel-inner">
	    <div class="carousel-item active">
	      <img src="https://i.ibb.co/y854MN4/6346166.jpg" class="d-block w-100" style='height: 600px'>
	    </div>
	    <div class="carousel-item">
	      <img src="https://i.ibb.co/y854MN4/6346166.jpg" class="d-block w-100" style='height: 600px'>
	    </div>
	    <div class="carousel-item">
	      <img src="https://i.ibb.co/y854MN4/6346166.jpg" class="d-block w-100" style='height: 600px'>
	    </div>
	  </div>
	  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="visually-hidden">Previous</span>
	  </button>
	  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="visually-hidden">Next</span>
	  </button>
	</div>

	<h5>Please log-in to your account For ticket bookings <%= link_to 'Log-in', new_user_session_path, class: 'btn btn-sm btn-success mt-1'%></h5>
	<h5>Or Sign-up to Create account with us <%= link_to 'Sign-up', new_user_registration_path, class: 'btn btn-sm btn-warning'%></h5>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ticket Booking</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <% if current_user.present? && current_user.role == 'super_admin' %>
          <li class="nav-item">
            <%= link_to "Assign Roles", assign_roles_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user.present? && current_user.role == 'admin' %>
          <li class="nav-item">
            <%= link_to "Block Users", users_list_for_admins_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user.present? && current_user.role == 'admin' %>
          <li class="nav-item">
            <%= link_to "Approve Bookings", all_bookings_bookings_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user.present? && current_user.role == 'user' %>
          <li class="nav-item">
            <%= link_to "Book slot", bookings_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <% if current_user.present? %>
        <%= current_user.email %> (<%= current_user.role %> ) 
        <% if current_user.is_blocked %>
          <span class="text-danger"> Blocked</span>
        <% end %>
        <p></p>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger mx-2" %>
      <% else %>
        <%= link_to 'Log-in', new_user_session_path , class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KatomaranTechnologies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/nav_bar" %>

    <center><span class="notice text-danger"><%= notice %></span>
    <span class="alert text-danger"><%= alert %></span></center>

    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/user_managment/assign_roles.html.erb
<div class="container">
	<h3>Users (<%= @users.count %>)</h3>
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Email</th>
	      <th scope="col">Role</th>
	      <th scope="col">Create on</th>
	      <th scope="col">Action</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @users.each_with_index do |user, index| %>
	  		<tr>
		      <th scope="row"><%= index+1 %></th>
		      <td><%= user.email %></td>
		      <td><%= user.role %></td>
		      <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
		      <td><button type="button" class="btn btn-warning btn-sms" data-bs-toggle="modal" data-bs-target="#exampleModal<%= user.id %>">
						  Update Role
						</button>
					</td>
		    </tr>

		    <!-- Modal -->
				<div class="modal fade" id="exampleModal<%= user.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h1 class="modal-title fs-5" id="exampleModalLabel">Role Update</h1>
				        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				      </div>
				      <%= form_tag(update_role_path, method: :put) do %>
					      <div class="modal-body">
					        Role: <%= select_tag :role, options_for_select([['Admin', 'admin'], ['User', 'user']]) %>
					        <%= submit_tag "Update", class:"btn btn-sm btn-primary", data: { turbolinks: false }  %>
					      </div>
					        <%= hidden_field :user, :id, value: user.id %>
				      <% end %>
				    </div>
				  </div>
				</div>
			<% end %>
	  </tbody>
	</table>
		
</div>

app/views/user_managment/users_list_for_admins.html.erb
<div class="container">
	<h3>Users (<%= @users.count %>)</h3>
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Email</th>
	      <th scope="col">Role</th>
	      <th scope="col">Create on</th>
	      <th scope="col">Blocked</th>
	      <th scope="col">Action</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @users.each_with_index do |user, index| %>
	  		<tr>
		      <th scope="row"><%= index+1 %></th>
		      <td><%= user.email %></td>
		      <td><%= user.role %></td>
		      <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
		      <td><%= user.is_blocked %></td>
		      <td>
			      <%= form_tag(block_user_path, method: :put) do %>
				      <%= hidden_field :user, :id, value: user.id %>
				      <%= hidden_field :user, :is_blocked, value: !user.is_blocked %>
				      <% button_name = user.is_blocked ? 'Un-Block' : 'Block' %>
							<%= submit_tag button_name, class:"btn btn-sm btn-primary", data: { turbolinks: false }  %>
						<% end %>
					</td>
		    </tr>
			<% end %>
	  </tbody>
	</table>
		
</div>